name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: bootstrap vcpkg
      run: ./vcpkg/bootstrap-vcpkg.sh 
    - name: install llvm
      run: ./vcpkg/vcpkg install llvm
    - name: build
      run: cmake .
